public enum TokenType {
        MATH, ADD, SUBTRACT, MULTIPLY, AND, OR, NOT, XOR, COPY, HALT, BRANCH, JUMP, CALL, PUSH, LOAD, RETURN, STORE, PEEK, POP, INTERRUPT, EQUAL, UNEQUAL, GREATER, LESS, GEQUAL, LEQUAL, SHIFT, LEFT, RIGHT, NUMBER, SEPERATOR, REGISTER
}
